### ISSUE TITLE
zoom issues in Safari and Firefox

### ISSUE THREAD

**Issue by fiestin** [publiclab/mapknitter#85] opened 2015-02-05 15:21 UTC
in Safari Zoom butttons were not working 
in Firefox zooming works but on the way it gets really funky, risk of vertigo

**Comment by jywarren** [comment] 2015-02-05 17:50
Hmm, I'm not sure -- it seems to be fine on Safari Version 6.1.5 (8537.77.4) -- see attached. Can you check what version you have? 

Re: Firefox, I've noticed that, and am opening an issue at the Leaflet.DistortableImage repository, which is what actually implements the distortion and zooming: https://github.com/publiclab/Leaflet.DistortableImage/issues/42

**Comment by jywarren** [comment] 2015-02-06 17:34
Anyone else with Safari notice this? @steviepubliclab or @mathewlippincott or @ebarry? Can you note what version and platform? Thanks.

**Comment by jywarren** [comment] 2015-02-09 22:59
Hi, folks - i'm sorry, as nobody's responded, I'm going to close this, but if you can reproduce with more detail, feel free to re-open! Thanks.

**Closed by jywarren** 2015-02-09 22:59 UTC
Labels: bug, mapknitter2
