### ISSUE TITLE
Remove anonymous from the Recent Authors

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#390] opened 2019-03-10 18:41 UTC
![image](https://user-images.githubusercontent.com/20972099/54089708-ddae0900-4391-11e9-9d06-2ae33caae29b.png)

**Comment by jywarren** [comment] 2019-03-11 14:54
ah also we should add `.distinct` to the query!

**Comment by aggarwal19** [comment] 2019-03-12 19:19
Hi @SidharthBansal , I want to solve this issue . Are you able to provide me some details about this ?
Thanks!

**Comment by gauravano** [comment] 2019-03-12 19:30
hey @aggarwal19, go ahead! Thanks!

**Comment by SidharthBansal** [comment] 2019-03-13 05:23
Please install Mapknitter.

**Comment by aggarwal19** [comment] 2019-03-14 21:33
okay

**Comment by aggarwal19** [comment] 2019-03-19 10:36
Hi ,
I did the installation process in linux , but by mistake I changed the file
permission of dev and usr folder due to this now I'm not able to use the
linux (I have to boot it again).So temporarily now I'm again doing the
installation process in windows . Are you able to tell me how to do
installation in windows ? or Is it complusory to use only linux distro ?

Thank you,
Shridhi

**Comment by gauravano** [comment] 2019-03-19 12:51
@aggarwal19 you can refer https://gorails.com/setup/windows/10 for Ruby on Rails installation in windows.  Thanks!

**Comment by aggarwal19** [comment] 2019-03-22 12:16
@gauravano After the installation process , what I have to do in this issue ?
Thanks!

**Comment by avsingh999** [comment] 2019-03-24 02:52
@aggarwal19 I think you need to install mysql2 in your local. Did you try this
 ```gem install mysql2  -v '0.3.21'```
thanks : )

**Comment by avsingh999** [comment] 2019-03-24 02:52
@aggarwal19 if you are not taking this can I solve this  :smile:

**Comment by aggarwal19** [comment] 2019-03-26 06:40
I used this command too but still it is showing me the same error .
Thanks!

**Comment by kaunair** [comment] 2019-03-26 12:03
You're missing mysql headers
run `sudo apt-get install libmysqlclient-dev`

**Comment by kaunair** [comment] 2019-03-26 12:05
Oh my bad I didn't realize you were using windows
Try this out https://dev.mysql.com/downloads/connector/c/

**Comment by divyabaid16** [comment] 2019-04-07 17:51
Hey!!!
Is this issue open to be worked upon?
I would like to help here.
Thanks!

**Comment by kaustubh-nair** [comment] 2019-04-07 18:00
Hey @divyabaid16 I believe this is a duplicate of issue https://github.com/publiclab/mapknitter/issues/389
which already has a pull: https://github.com/publiclab/mapknitter/pull/455 
Perhaps you can find another issue? If you need help in finding one please give a shout! 
Thanks

**Comment by kaustubh-nair** [comment] 2019-04-07 18:00
@SidharthBansal  lets close this one?

**Comment by divyabaid16** [comment] 2019-04-07 18:09
> Hey @divyabaid16 I believe this is a duplicate of issue #389
> which already has a pull: #455
> Perhaps you can find another issue? If you need help in finding one please give a shout!
> Thanks

Thank you @kaustubh-nair 
Can you please help me find some issues that I can solve here in mapknitter involving Javascript or anything else?

**Comment by kaustubh-nair** [comment] 2019-04-07 18:46
Looks like we are running a but low on javascript issues. @gauravano @sashadev-sky can we do something about this?
@divyabaid16 Perhaps you can give these a try in the meantime https://github.com/publiclab/mapknitter/issues/382, https://github.com/publiclab/mapknitter/issues/219
Thanks!

**Comment by sashadev-sky** [comment] 2019-04-11 13:04
@kaustubh-nair I try to not open too many FTOs at once so that I can make sure people get help on the ones I do but I think an endless source of FTOs is updating all of the hash rocket syntax key-value pairs to the newer syntax. What is your opinion on that?

**Comment by sashadev-sky** [comment] 2019-05-27 13:33
I'm going to close this one because @divyabaid16 is right that it's a duplicate and the other has a pull! I'm going to check-in with the user on their pull request there because they opened it a month ago

**Closed by sashadev-sky** 2019-05-27 13:33 UTC
Labels: bug, gsoc
