### ISSUE TITLE
Panning/zooming issues with new front page map

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#792] opened 2019-07-03 17:09 UTC
I found that clicking on a place name just under the map works, and the flyover is nice, but then additional interactions with the map (panning, zooming) seem to be linked to the original location in some way. To replicate, go to 

http://mapknitter-stable.laboratoriopublico.org/

Then click one of the places in the list below the map, like "Korea":

![image](https://user-images.githubusercontent.com/24359/60611205-c1e0cf80-9d93-11e9-9d86-38ceb11742da.png)

Then, once it's finished loading, click the "zoom out" button (<kbd>-</kbd>) in the upper left. It moves you back to the previous location!

**Comment by jywarren** [comment] 2019-07-03 17:11
@cesswairimu do you have any ideas about this? I think it's somehow not respecting the `fullhash` in the URL -- the hash (like `http://mapknitter-stable.laboratoriopublico.org/#8/18.315/-66.797/`) changes when you arrive at the new place, but when you zoom out again, it returns to the old location.

**Comment by cesswairimu** [comment] 2019-07-05 13:50
I think this was fixed in https://github.com/publiclab/mapknitter/pull/782. Could someone else check if this is still happening? I just tried and the issue is gone on my end.

**Comment by jywarren** [comment] 2019-07-05 13:59
Hi! It's still happening at http://mapknitter-stable.laboratoriopublico.org/,
let me make a gif. Thanks!

**Comment by cesswairimu** [comment] 2019-07-05 14:20
oh yeah I see

**Comment by jywarren** [comment] 2019-07-05 14:26
I think there are two inter-related issues. First that when you drag after
flying to a location, it kind of resists, and sends you back to the
original location. Second that if you try to zoom it does the same. But
they both seem to relate to the fullhash library...

**Comment by jywarren** [comment] 2019-07-05 18:21
I think i got the spinner issue...

**Comment by jywarren** [comment] 2019-07-05 19:10
OK, i resolved one of the zoom issues, i think... i am now using `map.flyTo(coords, zoom)` instead of just `map.flyTo(coords)`

**Comment by jywarren** [comment] 2019-07-05 19:18
I'll test out once it goes live on stable... but I think we are at least close enough to launch!

**Comment by jywarren** [comment] 2019-07-06 19:38
Hmm one variation of this error persists!

**Closed** 2019-07-10 16:19 UTC
Labels: bug
