### ISSUE TITLE
Firefox map not responding to commands

### ISSUE THREAD

**Issue by patcoyle** [publiclab/mapknitter#143] opened 2015-03-15 06:45 UTC
This single image map 
http://mapknitter.org/maps/dji-gimp-lens-corrected-image
In Firefox on Mac is not responding to zoom commands, or to resizing.

In Safari seems ok.

**Comment by jywarren** [comment] 2015-04-17 22:34
I'm now seeing this working on Firefox Linux (Ubuntu 14) v37.0.1. Checking again on a mac soon, but I think that's an improvement over a couple weeks ago.

**Comment by lotelx** [comment] 2015-04-23 02:25
I confirm that mapkintter is not working with firefox 36.0.4 on mac.
I can't use zoom commands neither modify the position of the photo.

I can't modify my map with only one picture:
http://mapknitter.org/maps/parque-augusta

**Comment by jywarren** [comment] 2015-05-05 18:12
Aha - I noticed in both FF/Mac 36.0.1 and 37.0.1 that this happens only after a zoom. At first the map is usable -- both panning and toolbar/transparency work. Hmm.

**Comment by jywarren** [comment] 2015-05-05 18:14
@lotelx @patcoyle this seems to be working again in FF/Mac 37.0.2 - can you confirm? I reproduced it in prev. versions and it does not seem to be an issue any more, so I'm going to close this, but please re-open if you still see it.

**Closed by jywarren** 2015-05-05 18:14 UTC
Labels: bug, in progress

**Comment by lotelx** [comment] 2015-05-05 19:50
Seems not working in my FF/Mac 37.02 :(

**Comment by jywarren** [comment] 2015-05-05 20:11
Do you also see that it works until you try to zoom? And can you check one
more time in private mode to clear the cache?
