### ISSUE TITLE
Mapknitter issues with file uploads

### ISSUE THREAD

**Issue by patcoyle** [publiclab/mapknitter#203] opened 2015-11-20 01:08 UTC
I observed file upload messages that request entity is too large for jpegs and pngs of Photoshop stitched comomposite images. See screen shot.
![ss issue w files various sizes less than 5mb](https://cloud.githubusercontent.com/assets/5530305/11289292/266beab4-8ee0-11e5-8eed-8cc7acb0cb48.jpg)

**Comment by jywarren** [comment] 2015-11-20 19:56
Hi, pat - I'm surprised that the 4.8 and 3.4 mb images were "too big" -- can you try those two smaller ones alone?

**Comment by jywarren** [comment] 2015-12-01 22:30
Sorry, forgot to close this after the Barnraising! Resolved; SSL-related.

**Comment by mathewlippincott** [comment] 2015-12-07 22:49
I'm seeing images hang in Mapknitter and not upload:
![screen shot 2015-12-07 at 2 47 14 pm](https://cloud.githubusercontent.com/assets/1203280/11642238/ac8fade6-9cf1-11e5-9c79-8983823161a4.png)

**Comment by mathewlippincott** [comment] 2015-12-07 22:52
i think the user Jan Cuipa is having the same issue, attempting to confirm in this thread:
https://groups.google.com/forum/#!topic/grassrootsmapping/1j7ch0dcq4A

**Comment by icarito** [comment] 2015-12-08 20:53
I had updated to ImageMagick 6.9.2, and found this in the nginx logs:

```
App 21789 stderr: convert convert:
App 21789 stderr: Unrecognized option
App 21789 stderr:  (-auto-orient)
App 21789 stderr: .
```

So I downgraded again (now it's running ImageMagick 6.7.7.10) and this started working again.
Previously it was running GraphicsMagick 1.3.16, which is a fork.
The idea was to see if it worked better at peak traffic to manage performance vs resources.

**Comment by icarito** [comment] 2015-12-09 13:33
The user has reported a different error that is consistent with https://github.com/phusion/passenger/issues/1426.  Our nginx.conf says `keepalive_timeout 65;` - but I have been unable to reproduce. Just in case, I'll double this digit, but can't test if it helps.

**Comment by gauravano** [comment] 2019-02-07 17:31
Hi! I tried to reproduce the issue but wasn't able to do so. Although, image is taking a bit time to upload like 4 min for 3.5 mb file but the upload was completed. @jywarren what do you think about this one? Thanks!

**Comment by gauravano** [comment] 2019-02-07 18:29
Although, I found some bugs like Image greater than 10 mb is also uploaded and other file formats like mp4 are allowed to be chosen and don't give error. I will open issues for them. Thanks!

**Comment by gauravano** [comment] 2019-02-07 18:31
@jywarren I tested all this on https://mapknitter.org/maps/lireille which seems to be a spam post so feel free to delete it.

**Comment by jywarren** [comment] 2019-02-07 18:46
Thanks! OK, let's close this and open new ones for faster upload,
restricting upload type, better error reporting and other refinements to
image upload handling. Thanks!

**Comment by gauravano** [comment] 2019-02-07 22:56
Hey @jywarren, I opened 2 separate issues for both problems #328 #329, so closing this one. Thanks!

**Closed by gauravano** 2019-02-07 22:56 UTC
Labels: bug, more-details-please
