### ISSUE TITLE
"There was an error." on create Map

### ISSUE THREAD

**Issue by DaveF63** [publiclab/mapknitter#297] opened 2019-01-12 13:07 UTC
### What happened just before the problem occurred
New user, not signed up. Using Win 7  Firefox latest 
Typed in title 
found location
Clicked not a robot
Clicked create Map 
Sent to "There was an error." page

Same occurs using other options.

Chatroom returns a "The connection has timed out" error.

--------
IE 10 won't even display the aerial image map or find a location.

**Comment by jywarren** [comment] 2019-01-16 15:30
Oops, sorry we didn't see this come in! We'll take a look ASAP; thank you for reporting!

**Comment by gauravano** [comment] 2019-01-25 21:54
Hi @jywarren, I tried to reproduce the issue but wasn't successful. @DaveF63 were you able to create the map after trying again? Thanks!

**Comment by gauravano** [comment] 2019-01-25 21:59
Hi @DaveF63 thanks for reporting the issue. @jywarren the error still exists. I am setting up mapknitter locally and will start working on issues, codebase exploration shortly. Thanks!

**Comment by gauravano** [comment] 2019-01-25 22:10
While creating map anonymously, some assets are not loading 

![map_create_error](https://user-images.githubusercontent.com/20878070/51775530-0e0c5180-211c-11e9-82cb-a7dc87ceb46e.png)

**Comment by cesswairimu** [comment] 2019-04-01 20:44
This seems to be working. I tried on Ubuntu 16.04.4 on both Chrome and Firefox. Both on the site and locally and its creating a map. @gauravano you please retest this when you get a minute. Will get a windows OS and test the same

**Comment by gauravano** [comment] 2019-04-03 13:11
Yup, working good now. Closing this issue then. @cesswairimu please re-open it if error exists in Windows OS. thanks!

**Closed by gauravano** 2019-04-03 13:11 UTC
Labels: bug, help wanted
